export const WITHDRAW_FROM_ACCOUNT = "WITHDRAW_FROM_ACCOUNT";
export const DEPOSIT_INTO_ACCOUNT = "DEPOSIT_INTO_ACCOUNT";
export const TOGGLE_INFO = "TOGGLE_INFO";
export const AUTHENTICATION = "AUTHENTICATION";
